// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	tasks "tasks-api/src/tasks"
)

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

// Search provides a mock function with given fields: ctx, filters
func (_m *Reader) Search(ctx context.Context, filters tasks.SearchFilters) ([]tasks.Task, error) {
	ret := _m.Called(ctx, filters)

	var r0 []tasks.Task
	if rf, ok := ret.Get(0).(func(context.Context, tasks.SearchFilters) []tasks.Task); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tasks.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, tasks.SearchFilters) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewReader interface {
	mock.TestingT
	Cleanup(func())
}

// NewReader creates a new instance of Reader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReader(t mockConstructorTestingTNewReader) *Reader {
	mock := &Reader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
